/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { AxiomV2Client, AxiomV2ClientInterface } from "../AxiomV2Client";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "sourceChainId",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "address",
        name: "callerAddr",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "querySchema",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "queryHash",
        type: "bytes32",
      },
    ],
    name: "AxiomV2Call",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "sourceChainId",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "callerAddr",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "querySchema",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "queryHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32[]",
        name: "axiomResults",
        type: "bytes32[]",
      },
      {
        internalType: "bytes",
        name: "callbackExtraData",
        type: "bytes",
      },
    ],
    name: "axiomV2Callback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "axiomV2QueryAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AxiomV2Client__factory {
  static readonly abi = _abi;
  static createInterface(): AxiomV2ClientInterface {
    return new Interface(_abi) as AxiomV2ClientInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AxiomV2Client {
    return new Contract(address, _abi, runner) as unknown as AxiomV2Client;
  }
}
